version: '3.8'

services:

  # -------------------
  # Jupyter + Spark
  # -------------------
  ed-pyspark-jupyter:
    image: jupyter/all-spark-notebook
    user: root
    container_name: all-spark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      JUPYTER_PORT: 8888
      SPARK_UI_PORT: 4040
      GRANT_SUDO: yes
    volumes:
      - ./notebooks:/home/jovyan/work        # Notebook tersimpan permanen
      - streaming_data:/data:rw
    networks:
      - kafka-network

  # -------------------
  # Kafka broker
  # -------------------
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    user: root                        # <- penting untuk fix permission
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'jAcf89sPTC-u9WrRL8LaWQ'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - kafka_kraft:/tmp/kraft-combined-logs
    networks:
      - kafka-network

  # -------------------
  # Kafka UI
  # -------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_READONLY=false
      - KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE=true
    networks:
      - kafka-network

# -------------------
# Volumes
# -------------------
volumes:
  streaming_data:
  kafka_kraft:

# -------------------
# Network internal
# -------------------
networks:
  kafka-network:
    driver: bridge
